### ISSUE TITLE
Packet Installing

### ISSUE THREAD

**Issue by SiDinhThoi** [zshhans/MSD-Mixer#3]
Hi authors,
if I use miniconda instead of conda, would the experiments run normally without any troubles?
Thanks

**Comment by zshhans** [comment]
Hi SiDinhThoi,

`conda` is a command line tool for python environment/package management. Anaconda and Miniconda are different python distributions equiped with `conda` by default. You can use either Anaconda or Miniconda to setup the environment as specified in the README.

Thank you for your interest in our work!
